### ISSUE TITLE
[Suggested Change / Recommendation] Change absolute import path Alias

### ISSUE THREAD

**Issue by eDonec** [theodorusclarence/ts-nextjs-tailwind-starter#108]
Hello Theodor,

I first would like to thank you for the work and effort that you have poured into this project!

Next, I would like to propose a minor change to the approach that you have taken towards the absolute import Aliases. Even though I understand the potential reasons behind your choice, I still think that a less opinionated approach would be better appreciated by the community. Therefore, I will be sending a pull request towards you. In it, I'll be making absolute imports simply absolute (i.e. instead of `@/components/something` we will have simply `components/something`).

If you see the change going well with your vision for this boilerplate then you may accept it, else just close the PR nothing personal 😃

Have a nice one !

**Comment by theodorusclarence** [comment]
Hi @eDonec,

Thanks for the suggestion, but for now I'll still keep the `@/` syntax because it is easier to distinguish imports from an external library (ex: `react`, `@headless-ui`) and from internal files (ex: `@/components/a`).

But, you're free to fork this project and add your common practice and use that template for yourself. 

Feel free to discuss something in the issue if you want to contribute something major, so your work won't go to waste.

Thanks!
